name: shop_fever
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.6
  image_picker: 0.8.3+2
  firebase_auth: 3.0.1
  firebase_core: 1.4.0
  pinput: 1.2.0
  country_code_picker: ^2.0.2
  custom_timer: ^0.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

