name: shop_fever
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.3
  get: 4.3.8
  image_picker: 0.8.3+2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  pinput: 1.2.0
  country_code_picker: ^2.0.2
  custom_timer: ^0.0.6
  logger: any
  carousel_slider: 4.0.0
  dots_indicator: 2.0.0
  google_maps_flutter: ^2.0.8
  get_storage: ^2.0.3
  hive: ^2.0.4
  hive_flutter: any
  path_provider: any
  location: 4.3.0
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  hive_generator: ^1.1.0
  build_runner: ^2.1.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

